# Stage 1: Build the WAR file using Maven
FROM maven:3.8.1-openjdk-11 AS build

WORKDIR /app
COPY . /app
RUN mvn clean package

# Stage 2: Copy the WAR file to Tomcat
FROM tomcat:9.0.53-jdk11-openjdk

COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/app.war
